name: Robins Patel
author: Ravi (Robins) Patel
markdown: redcarpet
pygments: true
description: I'm an entrepreneur from Boston where I have been working on Pitch for Windows. In May, I graduated from Boston University's College of Engineering.
greeting_title: Hi, I'm Robins.
greeting_text: I'm an engineer and entrepreneur from Boston. This is my homepage.
github: http://www.github.com/arnp
twitter: http://www.twitter.com/ravipatel
facebook: http://www.facebook.com/rnpatel7791
linkedin: http://www.linkedin.com/in/robinspatel
email: hi@robinspatel.com
location: 42°2'16"N   70°12'47"W
disqus: rnpatel

##Make sure to edit the above fields, especially for disqus. 

